from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any


if __package__ in {None, ""}:
    sys.path.append(str(Path(__file__).resolve().parents[2]))

from app.monster_catalog import (
    find_same_name_different_source_records,
    get_monsters_sorted_by_name,
    load_all_monster_records,
)
from tools.importers.monster_catalog_import import normalize_monster_name
from tools.importers.monster_manual_importer import (
    ImportPage,
    is_page_marker_line,
    normalize_line,
    slugify_name,
    title_case_name,
)
from tools.importers.monster_manual_schema import (
    ADD_BESTIARY_ENTRY_PAGE_RANGE,
    ADD_BESTIARY_SOURCE_ID,
    DEFAULT_ADD_BESTIARY_IMPORT_REPORT,
    DEFAULT_ADD_BESTIARY_MONSTERS_JSON,
    DEFAULT_ADD_BESTIARY_PACK_JSON,
    DEFAULT_ADD_BESTIARY_PDF,
    DEFAULT_ADD_BESTIARY_RAW_PAGES_DIR,
    DEFAULT_MONSTER_CATALOG_JSON,
    ResolvedMonsterSource,
    resolve_registered_monster_source,
)


SOURCE_PACK_ID = "imported.adventures_dark_and_deep_bestiary"
SOURCE_PACK_NAME = "Adventures Dark and Deep Bestiary Import"
SOURCE_TYPE = "pdf"
PACK_VERSION = "0.1.0"
AUTHOR = "Import generated by RPG World App tools"
LICENSE = "user-private-not-for-redistribution"
DESCRIPTION = (
    "Draft monster import generated from a user-provided Adventures Dark and Deep Bestiary PDF."
)
REQUIRED_STAT_FIELDS = (
    "Number",
    "Morale",
    "Hit Dice",
    "Armor Class",
    "Move",
    "Magic Resistance",
    "No. of Attacks",
    "Damage",
    "Size",
    "Intelligence",
    "Alignment",
    "X.P. Value",
)
OPTIONAL_STAT_FIELDS = (
    "Defenses",
    "Attacks",
    "Weaknesses",
    "Treasure Type",
    "Treasure Value",
    "Magical Treasure",
    "Turn as Type",
    "Evasion",
)
PROSE_FIELDS = (
    "General",
    "Combat",
    "Appearance",
    "Spellcasters",
    "See also",
)
ALL_LABELS = REQUIRED_STAT_FIELDS + OPTIONAL_STAT_FIELDS + PROSE_FIELDS
STAT_LABEL_SET = set(REQUIRED_STAT_FIELDS) | set(OPTIONAL_STAT_FIELDS)
PROSE_LABEL_SET = set(PROSE_FIELDS)
LABEL_PATTERN = re.compile(
    r"^(Number|Morale|Hit Dice|Armor Class|Move|Magic Resistance|No\. of Attacks|Damage|"
    r"Defenses|Attacks|Weaknesses|Size|Intelligence|Alignment|Treasure Type|Treasure Value|"
    r"Magical Treasure|X\.P\. Value|Turn as Type|Evasion|General|Combat|Appearance|Spellcasters|See also)\s*:\s*(.*)$",
    re.IGNORECASE,
)
PRINTED_PAGE_PATTERN = re.compile(r"^\d{1,4}$")
SKIP_HEADING_PATTERN = re.compile(r"^(appendix|index)\b", re.IGNORECASE)
TITLE_WORD_PATTERN = re.compile(r"[A-Za-z][A-Za-z'’\-.,()/]*")
SAFE_TAGS = {
    "undead": ("undead",),
    "plant": ("plant",),
    "construct": ("construct", "animated"),
    "animal": ("animal", "beast"),
    "humanoid": ("humanoid",),
    "flying": ("flying", "wings", "winged"),
    "aquatic": ("aquatic", "swimming", "water"),
    "extraplanar": ("demon", "devil", "astral", "abyss", "hell"),
}


@dataclass
class AddBestiaryEntry:
    heading: str
    actual_page_start: int
    actual_page_end: int
    printed_page: int | None
    raw_text: str


@dataclass
class RejectedAddBestiaryEntry:
    heading: str
    actual_page_start: int
    actual_page_end: int
    reason: str
    raw_text: str


@dataclass
class AddBestiaryImportResult:
    pack: dict[str, Any]
    monsters_payload: dict[str, Any]
    report_text: str
    accepted_count: int
    rejected_count: int
    partial_count: int
    duplicate_ids: list[str] = field(default_factory=list)
    same_name_warnings: list[str] = field(default_factory=list)
    missing_field_errors: list[str] = field(default_factory=list)
    rejected_entries: list[RejectedAddBestiaryEntry] = field(default_factory=list)
    pages_without_records: list[int] = field(default_factory=list)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Import single-entry monsters from the Adventures Dark and Deep Bestiary PDF."
    )
    parser.add_argument(
        "--input",
        default=str(DEFAULT_ADD_BESTIARY_PDF),
        help="Path to the Adventures Dark and Deep Bestiary PDF.",
    )
    parser.add_argument(
        "--pack-json",
        default=str(DEFAULT_ADD_BESTIARY_PACK_JSON),
        help="Path to write the pack.json metadata file.",
    )
    parser.add_argument(
        "--monsters-json",
        default=str(DEFAULT_ADD_BESTIARY_MONSTERS_JSON),
        help="Path to write the imported monsters.json file.",
    )
    parser.add_argument(
        "--raw-pages-dir",
        default=str(DEFAULT_ADD_BESTIARY_RAW_PAGES_DIR),
        help="Directory to write raw page text extracts.",
    )
    parser.add_argument(
        "--report",
        default=str(DEFAULT_ADD_BESTIARY_IMPORT_REPORT),
        help="Path to write the importer report.",
    )
    parser.add_argument(
        "--catalog",
        default=str(DEFAULT_MONSTER_CATALOG_JSON),
        help="Path to the existing core monster catalog for same-name comparisons.",
    )
    parser.add_argument(
        "--source-id",
        default=ADD_BESTIARY_SOURCE_ID,
        help="Registered monster source ID to use for source metadata and default path resolution.",
    )
    parser.add_argument(
        "--allow-inactive-source",
        action="store_true",
        help="Allow import from a source registry entry marked inactive, comparison-only, or deprecated.",
    )
    return parser.parse_args(argv)


def is_add_bestiary_entry_page(actual_page: int) -> bool:
    start_page, end_page = ADD_BESTIARY_ENTRY_PAGE_RANGE
    return start_page <= actual_page <= end_page


def canonical_label(label: str) -> str:
    normalized = " ".join(label.strip().split()).casefold()
    for item in ALL_LABELS:
        if item.casefold() == normalized:
            return item
    return label.strip()


def extract_pdf_pages(pdf_path: Path) -> list[ImportPage]:
    try:
        from pypdf import PdfReader
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError(
            "The ADD Bestiary importer requires pypdf for PDF extraction. "
            "Use the bundled Codex runtime Python or install pypdf in the environment used for this command."
        ) from exc

    reader = PdfReader(str(pdf_path))
    pages: list[ImportPage] = []
    for actual_page, page in enumerate(reader.pages, start=1):
        if not is_add_bestiary_entry_page(actual_page):
            continue
        pages.append(
            ImportPage(
                actual_page=actual_page,
                book=1,
                text=page.extract_text() or "",
            )
        )
    return pages


def write_raw_pages(pages: list[ImportPage], raw_pages_dir: Path) -> None:
    raw_pages_dir.mkdir(parents=True, exist_ok=True)
    for page in pages:
        output_path = raw_pages_dir / f"page_{page.actual_page:03d}.txt"
        output_path.write_text(
            page.text.replace("\r\n", "\n").replace("\r", "\n"),
            encoding="utf-8",
        )


def detect_printed_page_number(page_text: str) -> int | None:
    for raw_line in page_text.replace("\r\n", "\n").replace("\r", "\n").splitlines():
        line = normalize_line(raw_line)
        if PRINTED_PAGE_PATTERN.fullmatch(line):
            try:
                return int(line)
            except ValueError:
                return None
    return None


def cleaned_page_lines(page: ImportPage) -> list[str]:
    lines: list[str] = []
    for raw_line in page.text.replace("\r\n", "\n").replace("\r", "\n").splitlines():
        line = normalize_line(raw_line)
        if not line or is_page_marker_line(line):
            continue
        lines.append(line)
    return lines


def looks_like_title_line(line: str) -> bool:
    if not line or ":" in line or SKIP_HEADING_PATTERN.match(line):
        return False
    if line.endswith(".") or len(line) > 80:
        return False
    words = TITLE_WORD_PATTERN.findall(line)
    if not words or len(words) > 10:
        return False
    title_like = 0
    for word in words:
        stripped = word.strip("()[],.")
        if not stripped:
            continue
        if stripped.isupper():
            title_like += 1
        elif stripped[0].isupper():
            title_like += 1
        elif stripped.casefold() in {"of", "the", "and", "as", "or", "to", "in"}:
            title_like += 1
    return title_like >= max(1, len(words) - 1)


def find_label_positions(lines: list[str]) -> list[tuple[int, str, str]]:
    positions: list[tuple[int, str, str]] = []
    for index, line in enumerate(lines):
        match = LABEL_PATTERN.match(line)
        if not match:
            continue
        positions.append((index, canonical_label(match.group(1)), match.group(2).strip()))
    return positions


def split_entries_from_pages(pages: list[ImportPage]) -> tuple[list[AddBestiaryEntry], list[int]]:
    line_records: list[tuple[int, str]] = []
    raw_pages_by_number: dict[int, str] = {page.actual_page: page.text for page in pages}
    pages_with_titles: set[int] = set()
    for page in pages:
        lines = cleaned_page_lines(page)
        for line in lines:
            if looks_like_title_line(line):
                pages_with_titles.add(page.actual_page)
            line_records.append((page.actual_page, line))

    entries: list[AddBestiaryEntry] = []
    start_indexes: list[int] = []
    for index, (_, line) in enumerate(line_records):
        if not looks_like_title_line(line):
            continue
        lookahead = [candidate for _, candidate in line_records[index + 1 : index + 25]]
        if any(LABEL_PATTERN.match(candidate) for candidate in lookahead):
            start_indexes.append(index)

    for offset, start_index in enumerate(start_indexes):
        end_index = start_indexes[offset + 1] if offset + 1 < len(start_indexes) else len(line_records)
        chunk = line_records[start_index:end_index]
        if not chunk:
            continue
        actual_start = chunk[0][0]
        actual_end = chunk[-1][0]
        printed_page = detect_printed_page_number(raw_pages_by_number.get(actual_start, ""))
        entries.append(
            AddBestiaryEntry(
                heading=chunk[0][1],
                actual_page_start=actual_start,
                actual_page_end=actual_end,
                printed_page=printed_page,
                raw_text="\n".join(line for _, line in chunk),
            )
        )
    pages_without_records = sorted(
        page.actual_page
        for page in pages
        if page.actual_page not in pages_with_titles
    )
    return entries, pages_without_records


def parse_labeled_block(raw_text: str) -> tuple[dict[str, str], dict[str, str], Counter[str]]:
    lines = [line for line in raw_text.replace("\r\n", "\n").replace("\r", "\n").splitlines() if normalize_line(line)]
    label_positions = find_label_positions(lines)
    field_counts = Counter(label for _, label, _ in label_positions)
    stat_block: dict[str, str] = {}
    sections: dict[str, str] = {}
    for position_index, (line_index, label, remainder) in enumerate(label_positions):
        next_line_index = (
            label_positions[position_index + 1][0]
            if position_index + 1 < len(label_positions)
            else len(lines)
        )
        value_lines = [remainder] if remainder else []
        value_lines.extend(lines[line_index + 1 : next_line_index])
        value = " ".join(normalize_line(line) for line in value_lines if normalize_line(line)).strip()
        if label in STAT_LABEL_SET:
            stat_block[label] = value
        elif label in PROSE_LABEL_SET:
            sections[label] = value
    return stat_block, sections, field_counts


def infer_safe_tags(name: str, stat_block: dict[str, str], sections: dict[str, str]) -> list[str]:
    haystack = " ".join(
        filter(
            None,
            [
                name,
                stat_block.get("Move", ""),
                stat_block.get("Size", ""),
                sections.get("General", ""),
                sections.get("Appearance", ""),
            ],
        )
    ).casefold()
    tags: list[str] = []
    for tag, needles in SAFE_TAGS.items():
        if any(needle in haystack for needle in needles):
            tags.append(tag)
    return sorted(set(tags))


def infer_type(name: str) -> str | None:
    lowered = name.casefold()
    if "demon" in lowered or "devil" in lowered:
        return "fiend"
    if "dragon" in lowered:
        return "dragon"
    if "golem" in lowered or "animated" in lowered:
        return "construct"
    if "zombie" in lowered or "ghoul" in lowered or "wight" in lowered:
        return "undead"
    if "giant" in lowered:
        return "giant"
    return None


def build_monster_record(entry: AddBestiaryEntry, stat_block: dict[str, str], sections: dict[str, str]) -> dict[str, Any]:
    display_name = title_case_name(entry.heading)
    monster_id = f"add_bestiary.monster.{slugify_name(display_name)}"
    return {
        "id": monster_id,
        "name": display_name,
        "sort_name": entry.heading,
        "source": {
            "file": DEFAULT_ADD_BESTIARY_PDF.name,
            "name": SOURCE_PACK_NAME,
            "type": SOURCE_TYPE,
            "actual_page_start": entry.actual_page_start,
            "actual_page_end": entry.actual_page_end,
        },
        "source_pack": SOURCE_PACK_ID,
        "source_page_actual": entry.actual_page_start,
        "source_page_printed": entry.printed_page,
        "stat_block": stat_block,
        "sections": sections,
        "type": infer_type(display_name),
        "habitats": [],
        "regions": [],
        "tags": infer_safe_tags(display_name, stat_block, sections),
        "import_notes": [],
        "raw_text": entry.raw_text,
    }


def classify_entry(entry: AddBestiaryEntry) -> tuple[dict[str, Any] | None, RejectedAddBestiaryEntry | None, list[str]]:
    stat_block, sections, field_counts = parse_labeled_block(entry.raw_text)
    missing_fields = [field_name for field_name in REQUIRED_STAT_FIELDS if not stat_block.get(field_name)]
    notes: list[str] = []
    if any(field_counts.get(field_name, 0) > 1 for field_name in REQUIRED_STAT_FIELDS):
        return (
            None,
            RejectedAddBestiaryEntry(
                heading=entry.heading,
                actual_page_start=entry.actual_page_start,
                actual_page_end=entry.actual_page_end,
                reason="multi_variant_stat_block_not_supported_yet",
                raw_text=entry.raw_text,
            ),
            notes,
        )
    if missing_fields:
        return (
            None,
            RejectedAddBestiaryEntry(
                heading=entry.heading,
                actual_page_start=entry.actual_page_start,
                actual_page_end=entry.actual_page_end,
                reason=f"missing_required_stat_fields: {', '.join(missing_fields)}",
                raw_text=entry.raw_text,
            ),
            notes,
        )
    if not any(sections.get(field_name) for field_name in ("General", "Combat", "Appearance")):
        return (
            None,
            RejectedAddBestiaryEntry(
                heading=entry.heading,
                actual_page_start=entry.actual_page_start,
                actual_page_end=entry.actual_page_end,
                reason="missing_required_prose_section",
                raw_text=entry.raw_text,
            ),
            notes,
        )
    monster = build_monster_record(entry, stat_block, sections)
    return monster, None, notes


def validate_imported_monster_pack(
    pack_json_path: Path,
    monsters_json_path: Path,
) -> list[str]:
    errors: list[str] = []
    if not pack_json_path.exists():
        return [f"Missing pack metadata file: {pack_json_path}"]
    if not monsters_json_path.exists():
        return [f"Missing monsters file: {monsters_json_path}"]
    pack = json.loads(pack_json_path.read_text(encoding="utf-8"))
    payload = json.loads(monsters_json_path.read_text(encoding="utf-8"))
    monsters = payload.get("monsters", []) if isinstance(payload, dict) else payload
    if not isinstance(monsters, list):
        return ["monsters.json must contain a list or a top-level monsters list."]
    seen_ids: set[str] = set()
    for index, monster in enumerate(monsters, start=1):
        if not isinstance(monster, dict):
            errors.append(f"Monster {index} is not an object.")
            continue
        for field_name in ("id", "name", "source", "source_page_actual", "stat_block"):
            if field_name not in monster or monster.get(field_name) in (None, "", []):
                errors.append(f"Monster {index} missing required field: {field_name}")
        monster_id = str(monster.get("id") or "")
        if monster_id:
            if monster_id in seen_ids:
                errors.append(f"Duplicate monster id: {monster_id}")
            seen_ids.add(monster_id)
        stat_block = monster.get("stat_block", {})
        if isinstance(stat_block, dict):
            for field_name in REQUIRED_STAT_FIELDS:
                if not stat_block.get(field_name):
                    errors.append(f"{monster_id or monster.get('name')}: missing ADD Bestiary field {field_name}")
        else:
            errors.append(f"{monster_id or monster.get('name')}: stat_block must be an object")
    if pack.get("id") != SOURCE_PACK_ID:
        errors.append(f"pack.json id must be {SOURCE_PACK_ID}")
    return errors


def build_pack_metadata(source_info: ResolvedMonsterSource) -> dict[str, Any]:
    return {
        "id": SOURCE_PACK_ID,
        "name": SOURCE_PACK_NAME,
        "version": PACK_VERSION,
        "author": AUTHOR,
        "license": LICENSE,
        "enabled": True,
        "description": DESCRIPTION,
        "source_id": source_info.source_id,
        "source_title": source_info.source_title,
        "source_status": source_info.source_status,
    }


def build_monsters_payload(
    monsters: list[dict[str, Any]],
    source_pdf: Path,
    source_info: ResolvedMonsterSource,
) -> dict[str, Any]:
    return {
        "generated_at": datetime.now(UTC).isoformat(),
        "source_id": source_info.source_id,
        "source_title": source_info.source_title,
        "source_status": source_info.source_status,
        "source_pdf": source_pdf.name,
        "source_pack": SOURCE_PACK_ID,
        "monster_count": len(monsters),
        "monsters": monsters,
    }


def build_import_report(
    *,
    source_info: ResolvedMonsterSource,
    pack_json_path: Path,
    monsters_json_path: Path,
    raw_pages_dir: Path,
    report_path: Path,
    scanned_pages: list[int],
    skipped_pages: list[str],
    monsters: list[dict[str, Any]],
    rejected_entries: list[RejectedAddBestiaryEntry],
    duplicate_ids: list[str],
    same_name_warnings: list[str],
    missing_field_errors: list[str],
    pages_without_records: list[int],
) -> str:
    partial_count = sum(
        1
        for entry in rejected_entries
        if entry.reason == "multi_variant_stat_block_not_supported_yet"
    )
    lines = [
        "Adventures Dark and Deep Bestiary Import Report",
        "===============================================",
        "",
        "Importer: add_bestiary_importer",
        f"Source ID: {source_info.source_id or 'None'}",
        f"Source title: {source_info.source_title or 'None'}",
        f"Source status: {source_info.source_status or 'None'}",
        f"Source path used: {source_info.source_path}",
        f"Source path mode: {'direct override' if source_info.used_path_override else 'registry/default'}",
        f"Registered expected path: {source_info.path_display}",
        f"Input file present: {'yes' if source_info.exists else 'no'}",
        f"Pack output path: {pack_json_path}",
        f"Monsters output path: {monsters_json_path}",
        f"Raw pages directory: {raw_pages_dir}",
        f"Report output path: {report_path}",
        "",
        f"Actual PDF pages scanned: {scanned_pages[0]}-{scanned_pages[-1] if scanned_pages else 0}",
        f"Pages skipped: {', '.join(skipped_pages)}",
        f"Accepted monster count: {len(monsters)}",
        f"Rejected candidate count: {len(rejected_entries)}",
        f"Partial/unsupported multi-variant count: {partial_count}",
        f"Duplicate ID count: {len(duplicate_ids)}",
        f"Same-name/different-source warnings: {len(same_name_warnings)}",
        f"Missing field errors: {len(missing_field_errors)}",
        "",
        "Reminder: actual PDF pages were used, not printed page numbers.",
        "",
        "Same-name/different-source warnings:",
    ]
    lines.extend(f"- {warning}" for warning in same_name_warnings) if same_name_warnings else lines.append("- None")
    lines.extend(["", "Missing field errors:"])
    lines.extend(f"- {item}" for item in missing_field_errors) if missing_field_errors else lines.append("- None")
    lines.extend(["", "Duplicate IDs:"])
    lines.extend(f"- {item}" for item in duplicate_ids) if duplicate_ids else lines.append("- None")
    lines.extend(["", "Rejected records:"])
    if rejected_entries:
        lines.extend(
            f"- Page {entry.actual_page_start} [{entry.heading}]: {entry.reason}"
            for entry in rejected_entries
        )
    else:
        lines.append("- None")
    lines.extend(["", "Pages where no monster records were found:"])
    if pages_without_records:
        lines.append("- " + ", ".join(str(page) for page in pages_without_records))
    else:
        lines.append("- None")
    lines.extend(["", "Accepted monster examples:"])
    if monsters:
        lines.extend(
            f"- Page {monster['source_page_actual']}: {monster['name']} ({monster['id']})"
            for monster in monsters[:10]
        )
    else:
        lines.append("- None")
    lines.extend(
        [
            "",
            "Next recommended action:",
            f"- Review {report_path.name} before promoting this import pack into wider catalog workflows.",
            f"- Inspect raw page extracts under {raw_pages_dir} when a candidate entry is rejected.",
        ]
    )
    return "\n".join(lines) + "\n"


def build_import_from_pages(
    pages: list[ImportPage],
    *,
    source_info: ResolvedMonsterSource,
    existing_catalog_path: Path = DEFAULT_MONSTER_CATALOG_JSON,
    pack_json_path: Path = DEFAULT_ADD_BESTIARY_PACK_JSON,
    monsters_json_path: Path = DEFAULT_ADD_BESTIARY_MONSTERS_JSON,
    raw_pages_dir: Path = DEFAULT_ADD_BESTIARY_RAW_PAGES_DIR,
    report_path: Path = DEFAULT_ADD_BESTIARY_IMPORT_REPORT,
) -> AddBestiaryImportResult:
    entries, pages_without_records = split_entries_from_pages(pages)
    accepted_monsters: list[dict[str, Any]] = []
    rejected_entries: list[RejectedAddBestiaryEntry] = []
    missing_field_errors: list[str] = []

    for entry in entries:
        monster, rejected, _notes = classify_entry(entry)
        if rejected is not None:
            rejected_entries.append(rejected)
            if rejected.reason.startswith("missing_required_stat_fields"):
                missing_field_errors.append(
                    f"Page {rejected.actual_page_start} [{rejected.heading}]: {rejected.reason}"
                )
            continue
        if monster is not None:
            accepted_monsters.append(monster)

    duplicate_ids = sorted(
        monster_id
        for monster_id, count in Counter(monster["id"] for monster in accepted_monsters).items()
        if count > 1
    )
    if duplicate_ids:
        filtered: list[dict[str, Any]] = []
        seen_ids: set[str] = set()
        for monster in accepted_monsters:
            if monster["id"] in seen_ids:
                rejected_entries.append(
                    RejectedAddBestiaryEntry(
                        heading=monster["name"],
                        actual_page_start=monster["source_page_actual"],
                        actual_page_end=monster["source_page_actual"],
                        reason="duplicate_id_in_source",
                        raw_text=monster.get("raw_text", ""),
                    )
                )
                continue
            seen_ids.add(monster["id"])
            filtered.append(monster)
        accepted_monsters = filtered

    existing_records = load_all_monster_records(
        catalog_path=existing_catalog_path,
        content_packs_root=DEFAULT_ADD_BESTIARY_PACK_JSON.parents[1],
    )
    same_name_warnings = find_same_name_different_source_records(existing_records + accepted_monsters)

    pack = build_pack_metadata(source_info)
    monsters_payload = build_monsters_payload(
        accepted_monsters,
        source_info.source_path,
        source_info,
    )
    report_text = build_import_report(
        source_info=source_info,
        pack_json_path=pack_json_path,
        monsters_json_path=monsters_json_path,
        raw_pages_dir=raw_pages_dir,
        report_path=report_path,
        scanned_pages=[page.actual_page for page in pages],
        skipped_pages=["1-3", "439+"],
        monsters=accepted_monsters,
        rejected_entries=rejected_entries,
        duplicate_ids=duplicate_ids,
        same_name_warnings=same_name_warnings,
        missing_field_errors=missing_field_errors,
        pages_without_records=pages_without_records,
    )
    return AddBestiaryImportResult(
        pack=pack,
        monsters_payload=monsters_payload,
        report_text=report_text,
        accepted_count=len(accepted_monsters),
        rejected_count=len(rejected_entries),
        partial_count=sum(
            1 for entry in rejected_entries if entry.reason == "multi_variant_stat_block_not_supported_yet"
        ),
        duplicate_ids=duplicate_ids,
        same_name_warnings=same_name_warnings,
        missing_field_errors=missing_field_errors,
        rejected_entries=rejected_entries,
        pages_without_records=pages_without_records,
    )


def import_add_bestiary(
    pdf_path: Path = DEFAULT_ADD_BESTIARY_PDF,
    *,
    pack_json_path: Path = DEFAULT_ADD_BESTIARY_PACK_JSON,
    monsters_json_path: Path = DEFAULT_ADD_BESTIARY_MONSTERS_JSON,
    raw_pages_dir: Path = DEFAULT_ADD_BESTIARY_RAW_PAGES_DIR,
    report_path: Path = DEFAULT_ADD_BESTIARY_IMPORT_REPORT,
    existing_catalog_path: Path = DEFAULT_MONSTER_CATALOG_JSON,
    source_id: str = ADD_BESTIARY_SOURCE_ID,
    allow_inactive_source: bool = False,
) -> AddBestiaryImportResult:
    source_info = resolve_registered_monster_source(
        default_source_id=ADD_BESTIARY_SOURCE_ID,
        override_path=pdf_path if pdf_path != DEFAULT_ADD_BESTIARY_PDF else None,
        source_id=source_id,
        allow_inactive_source=allow_inactive_source,
    )
    source_info.source_path.parent.mkdir(parents=True, exist_ok=True)
    pages = extract_pdf_pages(source_info.source_path)
    write_raw_pages(pages, raw_pages_dir)
    result = build_import_from_pages(
        pages,
        source_info=source_info,
        existing_catalog_path=existing_catalog_path,
        pack_json_path=pack_json_path,
        monsters_json_path=monsters_json_path,
        raw_pages_dir=raw_pages_dir,
        report_path=report_path,
    )
    pack_json_path.parent.mkdir(parents=True, exist_ok=True)
    monsters_json_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.parent.mkdir(parents=True, exist_ok=True)
    pack_json_path.write_text(json.dumps(result.pack, indent=2, ensure_ascii=False), encoding="utf-8")
    monsters_json_path.write_text(
        json.dumps(result.monsters_payload, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    report_path.write_text(result.report_text, encoding="utf-8")
    return result


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        result = import_add_bestiary(
            Path(args.input),
            pack_json_path=Path(args.pack_json),
            monsters_json_path=Path(args.monsters_json),
            raw_pages_dir=Path(args.raw_pages_dir),
            report_path=Path(args.report),
            existing_catalog_path=Path(args.catalog),
            source_id=args.source_id,
            allow_inactive_source=args.allow_inactive_source,
        )
    except (FileNotFoundError, RuntimeError) as exc:
        print(exc)
        return 1

    print(
        f"Accepted {result.accepted_count} monsters. "
        f"Rejected={result.rejected_count}, multi-variant deferred={result.partial_count}."
    )
    print(f"Wrote pack: {args.pack_json}")
    print(f"Wrote monsters: {args.monsters_json}")
    print(f"Wrote report: {args.report}")
    print(f"Wrote raw page text to: {args.raw_pages_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
