from __future__ import annotations

import argparse
import json
import sys
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from pathlib import Path
import re
from typing import Any


if __package__ in {None, ""}:
    sys.path.append(str(Path(__file__).resolve().parents[2]))

from tools.importers.monster_manual_importer import is_page_marker_line, normalize_line
from tools.importers.monster_manual_schema import (
    DEFAULT_MEGADUNGEON_MONSTER_PDF,
    MEGADUNGEON_MONSTER_SOURCE_ID,
    PROJECT_ROOT,
    ResolvedMonsterSource,
    resolve_registered_monster_source,
)


MEGADUNGEON_MONSTER_SECTION_PAGES = (9, 105)
DEFAULT_PREVIEW_OUTPUT_PATH = (
    PROJECT_ROOT / "data" / "import_reports" / "megadungeon_monster_preview.json"
)
DEFAULT_PREVIEW_REPORT_PATH = (
    PROJECT_ROOT / "data" / "import_reports" / "megadungeon_monster_preview_report.txt"
)
DEFAULT_CONTENT_PACK_DIR = (
    PROJECT_ROOT / "data" / "content_packs" / "imported" / "megadungeon_monster_manual"
)
DEFAULT_CONTENT_PACK_JSON = DEFAULT_CONTENT_PACK_DIR / "pack.json"
DEFAULT_CONTENT_MONSTERS_JSON = DEFAULT_CONTENT_PACK_DIR / "monsters.json"
DEFAULT_CONTENT_PACK_REPORT_PATH = (
    PROJECT_ROOT / "data" / "import_reports" / "megadungeon_monster_content_pack_report.txt"
)
DEFAULT_RAW_TEXT_EXCERPT_LENGTH = 500
CONTENT_PACK_ID = "imported.megadungeon_monster_manual"
CONTENT_PACK_NAME = "Megadungeon Monster Manual Import"
CONTENT_PACK_VERSION = "0.1.0"
CONTENT_PACK_AUTHOR = "Import generated by RPG World App tools"
CONTENT_PACK_LICENSE = "user-private-not-for-redistribution"
CONTENT_PACK_DESCRIPTION = (
    "Separate imported monster content pack generated from a user-provided Megadungeon Monster Manual PDF."
)
CONTENT_PACK_IMPORTER_NAME = "megadungeon_monster_importer"
LABEL_ALIASES = {
    "noenc": "number_encountered",
    "alignment": "alignment",
    "movement": "movement",
    "armorclass": "armor_class",
    "hitdice": "hit_dice",
    "attacks": "attacks",
    "damage": "damage",
    "save": "save",
    "morale": "morale",
    "treasure": "treasure",
    "treasuretype": "treasure",
    "xp": "xp",
}
DISPLAY_LABELS = {
    "number_encountered": "No. Enc",
    "alignment": "Alignment",
    "movement": "Movement",
    "armor_class": "Armor Class",
    "hit_dice": "Hit Dice",
    "attacks": "Attacks",
    "damage": "Damage",
    "save": "Save",
    "morale": "Morale",
    "treasure": "Treasure",
    "xp": "XP",
}
PREVIEW_FIELD_MAP = {
    "number_encountered": "no_enc",
    "alignment": "alignment",
    "movement": "movement",
    "armor_class": "armor_class",
    "hit_dice": "hit_dice",
    "attacks": "attacks",
    "damage": "damage",
    "save": "save",
    "morale": "morale",
    "treasure": "treasure",
    "xp": "xp",
}
REQUIRED_STAT_KEYS = tuple(DISPLAY_LABELS.keys())
MUST_HAVE_STAT_KEYS = {
    "number_encountered",
    "alignment",
    "movement",
    "armor_class",
    "hit_dice",
    "xp",
}
HEADING_CONNECTORS = {"a", "an", "and", "for", "in", "of", "or", "the", "to"}
HEADING_IGNORE = {
    "Credits and Acknowledgements",
    "MEGADUNGEON",
    "MONSTER MANUAL",
    "Greg Gillespie",
    "Introduction",
    "Legal",
}
GENERIC_LABEL_PATTERN = re.compile(r"^\s*([A-Za-z. ]{2,40})\s*:\s*(.*)$")
TITLE_WORD_PATTERN = re.compile(r"^[A-Z][a-z]+(?:['-][A-Z][a-z]+)*$")
UPPERCASE_WORD_PATTERN = re.compile(r"^[A-Z]{2,}$")
HEADING_TOKEN_PATTERN = re.compile(r"[A-Za-z]+(?:['-][A-Za-z]+)*|[A-Z]{2,}|&|\d+")
LABEL_TOKEN_NORMALIZER = re.compile(r"[^a-z]+")
SLUG_TOKEN_PATTERN = re.compile(r"[^a-z0-9]+")


@dataclass
class ProbePage:
    actual_page: int
    text: str


@dataclass
class MegadungeonMonsterEntry:
    name: str
    source_id: str
    source_title: str
    actual_page_start: int
    actual_page_end: int
    raw_stat_block: str
    raw_text: str
    fields: dict[str, str]
    warnings: list[str] = field(default_factory=list)
    status: str = "parsed"
    confidence: str = "high"

    def to_preview_record(self, *, raw_text_excerpt_length: int = DEFAULT_RAW_TEXT_EXCERPT_LENGTH) -> dict[str, Any]:
        record = {
            "source_id": self.source_id,
            "source_title": self.source_title,
            "name": self.name,
            "slug": slugify_name(self.name),
            "actual_page_start": self.actual_page_start,
            "actual_page_end": self.actual_page_end,
            "raw_stat_block": self.raw_stat_block,
            "raw_text_excerpt": self.raw_text[:raw_text_excerpt_length],
            "raw_text": self.raw_text,
            "warnings": list(self.warnings),
            "status": self.status,
            "confidence": self.confidence,
        }
        for source_key, target_key in PREVIEW_FIELD_MAP.items():
            record[target_key] = self.fields.get(source_key, "")
        return record

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class MegadungeonProbeResult:
    source: ResolvedMonsterSource
    pages: list[int]
    entries: list[MegadungeonMonsterEntry]
    report_text: str
    candidate_headings_detected: int
    rejected_heading_count: int
    rejected_headings: list[str] = field(default_factory=list)


@dataclass
class MegadungeonDryRunPreviewResult:
    source: ResolvedMonsterSource
    pages: list[int]
    preview_records: list[dict[str, Any]]
    preview_path: Path
    report_path: Path
    report_text: str
    detected_entries: int
    parsed_entries: int
    partial_entries: int
    rejected_headings: int


@dataclass
class MegadungeonContentPackResult:
    source: ResolvedMonsterSource
    preview_records: list[dict[str, Any]]
    pack_metadata: dict[str, Any]
    monsters_payload: dict[str, Any]
    pack_json_path: Path
    monsters_json_path: Path
    report_path: Path
    report_text: str


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Probe or generate dry-run preview output for the Megadungeon Monster Manual PDF."
    )
    parser.add_argument(
        "pdf_path",
        nargs="?",
        default=None,
        help="Optional direct path override for the Megadungeon Monster Manual PDF.",
    )
    parser.add_argument(
        "--probe",
        action="store_true",
        help="Run read-only probe mode and print detected entries without writing preview files.",
    )
    parser.add_argument(
        "--dry-run-preview",
        action="store_true",
        help="Write a separate preview JSON/report pair without modifying live monster catalogs.",
    )
    parser.add_argument(
        "--write-content-pack",
        action="store_true",
        help="Write a separate imported content pack without modifying live monster catalogs.",
    )
    parser.add_argument(
        "--pages",
        nargs="*",
        type=int,
        default=None,
        help="Actual PDF pages to probe, for example --pages 9 11 83.",
    )
    parser.add_argument(
        "--preview-output",
        default=str(DEFAULT_PREVIEW_OUTPUT_PATH),
        help="Path for the dry-run preview JSON output.",
    )
    parser.add_argument(
        "--preview-report",
        default=str(DEFAULT_PREVIEW_REPORT_PATH),
        help="Path for the dry-run preview text report.",
    )
    parser.add_argument(
        "--pack-json",
        default=str(DEFAULT_CONTENT_PACK_JSON),
        help="Path for the Megadungeon content-pack metadata file.",
    )
    parser.add_argument(
        "--monsters-json",
        default=str(DEFAULT_CONTENT_MONSTERS_JSON),
        help="Path for the Megadungeon content-pack monsters payload file.",
    )
    parser.add_argument(
        "--content-pack-report",
        default=str(DEFAULT_CONTENT_PACK_REPORT_PATH),
        help="Path for the Megadungeon content-pack report text file.",
    )
    parser.add_argument(
        "--source-id",
        default=MEGADUNGEON_MONSTER_SOURCE_ID,
        help="Registered monster source ID used for source metadata and default path resolution.",
    )
    parser.add_argument(
        "--allow-inactive-source",
        action="store_true",
        help="Allow probing a source registry entry marked inactive or comparison-only.",
    )
    return parser.parse_args(argv)


def default_actual_pages() -> list[int]:
    start, end = MEGADUNGEON_MONSTER_SECTION_PAGES
    return list(range(start, end + 1))


def resolve_probe_source(
    pdf_path: Path | None = None,
    *,
    source_id: str = MEGADUNGEON_MONSTER_SOURCE_ID,
    allow_inactive_source: bool = False,
) -> ResolvedMonsterSource:
    return resolve_registered_monster_source(
        default_source_id=MEGADUNGEON_MONSTER_SOURCE_ID,
        override_path=pdf_path,
        source_id=source_id,
        allow_inactive_source=allow_inactive_source,
    )


def extract_probe_pages(
    pdf_path: Path,
    actual_pages: list[int] | None = None,
) -> list[ProbePage]:
    try:
        from pypdf import PdfReader
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError(
            "The Megadungeon probe requires pypdf for PDF extraction. "
            "Use the bundled Codex runtime Python or install pypdf in the "
            "environment used for this tooling command."
        ) from exc

    reader = PdfReader(str(pdf_path))
    pages_to_read = actual_pages or default_actual_pages()

    pages: list[ProbePage] = []
    for actual_page in pages_to_read:
        if actual_page < 1 or actual_page > len(reader.pages):
            raise ValueError(
                f"Requested page {actual_page} is outside the PDF page range 1-{len(reader.pages)}."
            )
        text = reader.pages[actual_page - 1].extract_text() or ""
        pages.append(ProbePage(actual_page=actual_page, text=text))
    return pages


def normalize_label_token(label: str) -> str:
    return LABEL_TOKEN_NORMALIZER.sub("", normalize_line(label).lower())


def parse_stat_label_line(line: str) -> tuple[str, str] | None:
    match = GENERIC_LABEL_PATTERN.match(line)
    if not match:
        return None
    key = LABEL_ALIASES.get(normalize_label_token(match.group(1)))
    if key is None:
        return None
    return key, normalize_line(match.group(2))


def is_stat_continuation_line(line: str) -> bool:
    stripped = normalize_line(line)
    if not stripped:
        return False
    if stripped.startswith("("):
        return True
    return False


def tokenize_heading(line: str) -> list[str]:
    return HEADING_TOKEN_PATTERN.findall(line)


def slugify_name(name: str) -> str:
    base = SLUG_TOKEN_PATTERN.sub("", name.lower())
    return base or "unknown_megadungeon_monster"


def page_looks_like_non_monster_frontmatter(page: ProbePage) -> bool:
    lines = [normalize_line(line) for line in page.text.replace("\r\n", "\n").replace("\r", "\n").splitlines()]
    lines = [line for line in lines if line and not is_page_marker_line(line)]
    if not lines:
        return True
    combined = "\n".join(lines[:20])
    if "Introduction" in combined:
        return True
    if "Credits and Acknowledgements" in combined:
        return True
    if "Legal" in combined:
        return True
    dot_leader_hits = sum(1 for line in lines[:40] if "..." in line or " . " in line or "................................" in line)
    if dot_leader_hits >= 3:
        return True
    return False


def is_title_case_heading_candidate(line: str) -> bool:
    stripped = normalize_line(line)
    if not stripped or ":" in stripped or stripped in HEADING_IGNORE:
        return False
    if stripped.endswith((".", ";", ",")):
        return False
    tokens = tokenize_heading(stripped)
    if not tokens or len(tokens) > 6:
        return False

    saw_title_word = False
    for token in tokens:
        lower = token.lower()
        if lower in HEADING_CONNECTORS:
            continue
        if token == "&":
            continue
        if token.isdigit():
            return False
        if TITLE_WORD_PATTERN.fullmatch(token) or UPPERCASE_WORD_PATTERN.fullmatch(token):
            saw_title_word = True
            continue
        return False
    return saw_title_word


def has_required_stat_block_nearby(
    lines: list[tuple[int, str]],
    start_index: int,
    *,
    lookahead: int = 18,
    min_labels: int = 8,
) -> bool:
    found: set[str] = set()
    steps = 0
    for _, candidate in lines[start_index + 1 :]:
        stripped = normalize_line(candidate)
        if not stripped:
            continue
        steps += 1
        parsed = parse_stat_label_line(stripped)
        if parsed is not None:
            found.add(parsed[0])
            if len(found) >= min_labels and MUST_HAVE_STAT_KEYS.issubset(found):
                return True
            continue
        if is_title_case_heading_candidate(stripped):
            return False
        if steps >= lookahead:
            break
    return False


def build_normalized_line_index(pages: list[ProbePage]) -> list[tuple[int, str]]:
    indexed_lines: list[tuple[int, str]] = []
    for page in pages:
        if page_looks_like_non_monster_frontmatter(page):
            continue
        for raw_line in page.text.replace("\r\n", "\n").replace("\r", "\n").splitlines():
            line = normalize_line(raw_line)
            if not line or is_page_marker_line(line):
                continue
            indexed_lines.append((page.actual_page, line))
    return indexed_lines


def classify_entry_status(fields: dict[str, str], warnings: list[str]) -> tuple[str, str]:
    if not fields:
        return "rejected", "low"
    if any(warning.startswith("missing_stat_labels:") for warning in warnings):
        return "partial", "medium"
    return "parsed", "high"


def split_entries_from_pages(
    pages: list[ProbePage],
) -> tuple[list[MegadungeonMonsterEntry], int, list[str]]:
    indexed_lines = build_normalized_line_index(pages)
    heading_candidates = [
        line
        for _, line in indexed_lines
        if is_title_case_heading_candidate(line)
    ]
    heading_indexes: list[int] = []
    rejected_headings: list[str] = []
    for index, (_, line) in enumerate(indexed_lines):
        if not is_title_case_heading_candidate(line):
            continue
        if has_required_stat_block_nearby(indexed_lines, index):
            heading_indexes.append(index)
        else:
            rejected_headings.append(line)

    entries: list[MegadungeonMonsterEntry] = []
    for position, start_index in enumerate(heading_indexes):
        end_index = (
            heading_indexes[position + 1]
            if position + 1 < len(heading_indexes)
            else len(indexed_lines)
        )
        entry_lines = indexed_lines[start_index:end_index]
        if not entry_lines:
            continue
        entries.append(parse_entry_lines(entry_lines))
    return entries, len(heading_candidates), rejected_headings


def parse_entry_lines(entry_lines: list[tuple[int, str]]) -> MegadungeonMonsterEntry:
    start_page = entry_lines[0][0]
    end_page = entry_lines[-1][0]
    name = entry_lines[0][1]
    body_lines = [line for _, line in entry_lines[1:]]
    raw_text = "\n".join(line for _, line in entry_lines)

    fields: dict[str, str] = {}
    warnings: list[str] = []
    raw_stat_lines: list[str] = []
    duplicate_keys: list[str] = []
    collecting_stat_block = True
    last_key: str | None = None

    for line in body_lines:
        parsed = parse_stat_label_line(line)
        if parsed is not None and collecting_stat_block:
            key, value = parsed
            if key in fields:
                duplicate_keys.append(key)
            fields[key] = value
            raw_stat_lines.append(line)
            last_key = key
            continue
        if collecting_stat_block and last_key is not None and is_stat_continuation_line(line):
            fields[last_key] = f"{fields[last_key]} {normalize_line(line)}".strip()
            raw_stat_lines.append(line)
            continue
        collecting_stat_block = False

    if not raw_stat_lines:
        warnings.append("no_stat_block_detected")

    missing_keys = [key for key in REQUIRED_STAT_KEYS if key not in fields]
    if missing_keys:
        warnings.append(
            "missing_stat_labels: " + ", ".join(DISPLAY_LABELS[key] for key in missing_keys)
        )
    if duplicate_keys:
        warnings.append(
            "duplicate_stat_labels: "
            + ", ".join(DISPLAY_LABELS[key] for key in sorted(set(duplicate_keys)))
        )
    if end_page > start_page:
        warnings.append("entry_spans_multiple_pages")

    status, confidence = classify_entry_status(fields, warnings)
    return MegadungeonMonsterEntry(
        name=name,
        source_id=MEGADUNGEON_MONSTER_SOURCE_ID,
        source_title="Megadungeon Monster Manual",
        actual_page_start=start_page,
        actual_page_end=end_page,
        raw_stat_block="\n".join(raw_stat_lines),
        raw_text=raw_text,
        fields=fields,
        warnings=warnings,
        status=status,
        confidence=confidence,
    )


def build_probe_report(
    source: ResolvedMonsterSource,
    pages: list[ProbePage],
    entries: list[MegadungeonMonsterEntry],
    *,
    candidate_headings_detected: int,
    rejected_headings: list[str],
) -> str:
    parsed_entries = sum(1 for entry in entries if entry.status == "parsed")
    partial_entries = sum(1 for entry in entries if entry.status == "partial")
    lines = [
        "Megadungeon Monster Probe",
        "=========================",
        "",
        f"Source ID: {source.source_id}",
        f"Source title: {source.source_title}",
        f"Source status: {source.source_status}",
        f"Source path mode: {'direct override' if source.used_path_override else 'registry default'}",
        f"Source path: {source.path_display}",
        f"Pages probed: {', '.join(str(page.actual_page) for page in pages) if pages else '(none)'}",
        f"Candidate headings detected: {candidate_headings_detected}",
        f"Rejected headings: {len(rejected_headings)}",
        f"Entries detected: {len(entries)}",
        f"Parsed entries: {parsed_entries}",
        f"Partial entries: {partial_entries}",
    ]
    for entry in entries:
        lines.extend(
            [
                "",
                f"{entry.name} (pages {entry.actual_page_start}-{entry.actual_page_end})",
                f"Status: {entry.status}",
                f"Confidence: {entry.confidence}",
                f"Warnings: {', '.join(entry.warnings) if entry.warnings else 'None'}",
            ]
        )
        for key in REQUIRED_STAT_KEYS:
            if key in entry.fields:
                lines.append(f"- {DISPLAY_LABELS[key]}: {entry.fields[key]}")
    if rejected_headings:
        lines.extend(["", "Rejected headings:", *[f"- {heading}" for heading in rejected_headings[:20]]])
    return "\n".join(lines) + "\n"


def build_preview_report(
    source: ResolvedMonsterSource,
    pages: list[int],
    preview_records: list[dict[str, Any]],
    *,
    candidate_headings_detected: int,
    rejected_heading_count: int,
    preview_path: Path,
    report_path: Path,
) -> str:
    parsed_entries = sum(1 for record in preview_records if record["status"] == "parsed")
    partial_entries = sum(1 for record in preview_records if record["status"] == "partial")
    lines = [
        "Megadungeon Monster Dry-Run Preview",
        "===================================",
        "",
        f"Source ID: {source.source_id}",
        f"Source title: {source.source_title}",
        f"Source status: {source.source_status}",
        f"Source path mode: {'direct override' if source.used_path_override else 'registry default'}",
        f"Source path: {source.path_display}",
        f"Pages scanned: {pages[0]}-{pages[-1]}" if pages else "Pages scanned: (none)",
        f"Candidate headings detected: {candidate_headings_detected}",
        f"Rejected headings: {rejected_heading_count}",
        f"Preview records: {len(preview_records)}",
        f"Parsed entries: {parsed_entries}",
        f"Partial entries: {partial_entries}",
        f"Preview output: {preview_path}",
        f"Preview report: {report_path}",
    ]
    sample_names = ("Aarakocra", "Rock Manta")
    by_name = {record["name"]: record for record in preview_records}
    for sample_name in sample_names:
        record = by_name.get(sample_name)
        if record is None:
            continue
        lines.extend(
            [
                "",
                f"{sample_name} preview sample",
                f"- slug: {record['slug']}",
                f"- pages: {record['actual_page_start']}-{record['actual_page_end']}",
                f"- no_enc: {record['no_enc']}",
                f"- movement: {record['movement']}",
                f"- xp: {record['xp']}",
                f"- status: {record['status']}",
                f"- warnings: {', '.join(record['warnings']) if record['warnings'] else 'None'}",
            ]
        )
    partial_records = [record for record in preview_records if record["status"] != "parsed"]
    if partial_records:
        lines.append("")
        lines.append("Partial record review")
        for record in partial_records[:10]:
            lines.append(
                f"- {record['name']} (pages {record['actual_page_start']}-{record['actual_page_end']}): "
                f"{', '.join(record['warnings']) if record['warnings'] else 'No warnings recorded'}"
            )
    return "\n".join(lines) + "\n"


def now_utc_iso() -> str:
    return datetime.now(UTC).isoformat()


def build_content_pack_metadata(
    source: ResolvedMonsterSource,
    *,
    record_count: int,
    generated_at: str,
) -> dict[str, Any]:
    return {
        "pack_id": source.source_id,
        "id": CONTENT_PACK_ID,
        "name": CONTENT_PACK_NAME,
        "version": CONTENT_PACK_VERSION,
        "author": CONTENT_PACK_AUTHOR,
        "license": CONTENT_PACK_LICENSE,
        "enabled": True,
        "description": CONTENT_PACK_DESCRIPTION,
        "source_id": source.source_id,
        "source_title": source.source_title,
        "source_status": source.source_status,
        "generated_at": generated_at,
        "record_count": record_count,
        "importer_name": CONTENT_PACK_IMPORTER_NAME,
        "notes": "Separate imported content pack only. This does not modify or merge into the core MandBmaster monster catalog.",
    }


def build_content_pack_record(
    preview_record: dict[str, Any],
    *,
    source_file: str,
) -> dict[str, Any]:
    return {
        "id": f"megadungeon.monster.{preview_record['slug']}",
        "name": preview_record["name"],
        "sort_name": preview_record["name"].upper(),
        "slug": preview_record["slug"],
        "source_id": preview_record["source_id"],
        "source_title": preview_record["source_title"],
        "source_file": source_file,
        "source_pack": CONTENT_PACK_ID,
        "source_page_actual": preview_record["actual_page_start"],
        "source_page_end": preview_record["actual_page_end"],
        "source": {
            "file": source_file,
            "name": preview_record["source_title"],
            "type": "pdf",
            "source_id": preview_record["source_id"],
            "actual_page_start": preview_record["actual_page_start"],
            "actual_page_end": preview_record["actual_page_end"],
        },
        "actual_page_start": preview_record["actual_page_start"],
        "actual_page_end": preview_record["actual_page_end"],
        "no_enc": preview_record["no_enc"],
        "alignment": preview_record["alignment"],
        "movement": preview_record["movement"],
        "armor_class": preview_record["armor_class"],
        "hit_dice": preview_record["hit_dice"],
        "attacks": preview_record["attacks"],
        "damage": preview_record["damage"],
        "save": preview_record["save"],
        "morale": preview_record["morale"],
        "treasure": preview_record["treasure"],
        "xp": preview_record["xp"],
        "raw_stat_block": preview_record["raw_stat_block"],
        "description": preview_record["raw_text_excerpt"],
        "source_text_excerpt": preview_record["raw_text_excerpt"],
        "raw_text": preview_record["raw_text"],
        "warnings": list(preview_record["warnings"]),
        "parser_status": preview_record["status"],
        "confidence": preview_record["confidence"],
    }


def build_content_pack_payload(
    records: list[dict[str, Any]],
    *,
    source: ResolvedMonsterSource,
    generated_at: str,
) -> dict[str, Any]:
    monsters = [
        build_content_pack_record(record, source_file=source.source_path.name)
        for record in records
    ]
    return {
        "generated_at": generated_at,
        "source_id": source.source_id,
        "source_title": source.source_title,
        "source_status": source.source_status,
        "source_pdf": source.source_path.name,
        "source_pack": CONTENT_PACK_ID,
        "monster_count": len(monsters),
        "monsters": monsters,
    }


def build_content_pack_report(
    *,
    source: ResolvedMonsterSource,
    pack_json_path: Path,
    monsters_json_path: Path,
    preview_path: Path,
    preview_report_path: Path,
    generated_at: str,
    preview_records: list[dict[str, Any]],
    rejected_heading_count: int,
) -> str:
    parsed_count = sum(1 for record in preview_records if record["status"] == "parsed")
    partial_count = sum(1 for record in preview_records if record["status"] == "partial")
    lines = [
        "Megadungeon Monster Content Pack Report",
        "=======================================",
        "",
        f"Importer: {CONTENT_PACK_IMPORTER_NAME}",
        f"Source ID: {source.source_id}",
        f"Source title: {source.source_title}",
        f"Source status: {source.source_status}",
        f"Source path used: {source.source_path}",
        f"Source path mode: {'direct override' if source.used_path_override else 'registry default'}",
        f"Registered expected path: {source.path_display}",
        f"Generated at: {generated_at}",
        f"Preview JSON path: {preview_path}",
        f"Preview report path: {preview_report_path}",
        f"Pack metadata path: {pack_json_path}",
        f"Pack monsters path: {monsters_json_path}",
        "",
        f"Record count: {len(preview_records)}",
        f"Parsed count: {parsed_count}",
        f"Partial count: {partial_count}",
        f"Rejected heading count: {rejected_heading_count}",
        "",
        "Reminder: this is a separate imported content pack and does not modify the core MandBmaster monster catalog.",
    ]
    return "\n".join(lines) + "\n"


def probe_megadungeon(
    *,
    pdf_path: Path | None = None,
    actual_pages: list[int] | None = None,
    source_id: str = MEGADUNGEON_MONSTER_SOURCE_ID,
    allow_inactive_source: bool = False,
) -> MegadungeonProbeResult:
    source = resolve_probe_source(
        pdf_path,
        source_id=source_id,
        allow_inactive_source=allow_inactive_source,
    )
    pages = extract_probe_pages(source.source_path, actual_pages=actual_pages)
    entries, candidate_headings_detected, rejected_headings = split_entries_from_pages(pages)
    for entry in entries:
        entry.source_title = source.source_title or "Megadungeon Monster Manual"
    report_text = build_probe_report(
        source,
        pages,
        entries,
        candidate_headings_detected=candidate_headings_detected,
        rejected_headings=rejected_headings,
    )
    return MegadungeonProbeResult(
        source=source,
        pages=[page.actual_page for page in pages],
        entries=entries,
        report_text=report_text,
        candidate_headings_detected=candidate_headings_detected,
        rejected_heading_count=len(rejected_headings),
        rejected_headings=rejected_headings,
    )


def write_text_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def write_json_file(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")


def generate_dry_run_preview(
    *,
    pdf_path: Path | None = None,
    actual_pages: list[int] | None = None,
    preview_output_path: Path = DEFAULT_PREVIEW_OUTPUT_PATH,
    preview_report_path: Path = DEFAULT_PREVIEW_REPORT_PATH,
    source_id: str = MEGADUNGEON_MONSTER_SOURCE_ID,
    allow_inactive_source: bool = False,
) -> MegadungeonDryRunPreviewResult:
    probe_result = probe_megadungeon(
        pdf_path=pdf_path,
        actual_pages=actual_pages,
        source_id=source_id,
        allow_inactive_source=allow_inactive_source,
    )
    preview_records = [
        entry.to_preview_record()
        for entry in probe_result.entries
    ]
    report_text = build_preview_report(
        probe_result.source,
        probe_result.pages,
        preview_records,
        candidate_headings_detected=probe_result.candidate_headings_detected,
        rejected_heading_count=probe_result.rejected_heading_count,
        preview_path=preview_output_path,
        report_path=preview_report_path,
    )
    write_json_file(preview_output_path, preview_records)
    write_text_file(preview_report_path, report_text)
    parsed_entries = sum(1 for record in preview_records if record["status"] == "parsed")
    partial_entries = sum(1 for record in preview_records if record["status"] == "partial")
    return MegadungeonDryRunPreviewResult(
        source=probe_result.source,
        pages=probe_result.pages,
        preview_records=preview_records,
        preview_path=preview_output_path,
        report_path=preview_report_path,
        report_text=report_text,
        detected_entries=len(preview_records),
        parsed_entries=parsed_entries,
        partial_entries=partial_entries,
        rejected_headings=probe_result.rejected_heading_count,
    )


def write_content_pack(
    *,
    pdf_path: Path | None = None,
    actual_pages: list[int] | None = None,
    preview_output_path: Path = DEFAULT_PREVIEW_OUTPUT_PATH,
    preview_report_path: Path = DEFAULT_PREVIEW_REPORT_PATH,
    pack_json_path: Path = DEFAULT_CONTENT_PACK_JSON,
    monsters_json_path: Path = DEFAULT_CONTENT_MONSTERS_JSON,
    report_path: Path = DEFAULT_CONTENT_PACK_REPORT_PATH,
    source_id: str = MEGADUNGEON_MONSTER_SOURCE_ID,
    allow_inactive_source: bool = False,
    generated_at: str | None = None,
) -> MegadungeonContentPackResult:
    effective_generated_at = generated_at or now_utc_iso()
    preview_result = generate_dry_run_preview(
        pdf_path=pdf_path,
        actual_pages=actual_pages,
        preview_output_path=preview_output_path,
        preview_report_path=preview_report_path,
        source_id=source_id,
        allow_inactive_source=allow_inactive_source,
    )
    pack_metadata = build_content_pack_metadata(
        preview_result.source,
        record_count=len(preview_result.preview_records),
        generated_at=effective_generated_at,
    )
    monsters_payload = build_content_pack_payload(
        preview_result.preview_records,
        source=preview_result.source,
        generated_at=effective_generated_at,
    )
    report_text = build_content_pack_report(
        source=preview_result.source,
        pack_json_path=pack_json_path,
        monsters_json_path=monsters_json_path,
        preview_path=preview_result.preview_path,
        preview_report_path=preview_result.report_path,
        generated_at=effective_generated_at,
        preview_records=preview_result.preview_records,
        rejected_heading_count=preview_result.rejected_headings,
    )
    write_json_file(pack_json_path, pack_metadata)
    write_json_file(monsters_json_path, monsters_payload)
    write_text_file(report_path, report_text)
    return MegadungeonContentPackResult(
        source=preview_result.source,
        preview_records=preview_result.preview_records,
        pack_metadata=pack_metadata,
        monsters_payload=monsters_payload,
        pack_json_path=pack_json_path,
        monsters_json_path=monsters_json_path,
        report_path=report_path,
        report_text=report_text,
    )


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    selected_modes = [args.probe, args.dry_run_preview, args.write_content_pack]
    if sum(1 for mode in selected_modes if mode) != 1:
        print(
            "Choose exactly one mode: --probe, --dry-run-preview, or --write-content-pack.",
            file=sys.stderr,
        )
        return 2

    override_path = Path(args.pdf_path) if args.pdf_path else None
    try:
        if args.probe:
            result = probe_megadungeon(
                pdf_path=override_path,
                actual_pages=args.pages,
                source_id=args.source_id,
                allow_inactive_source=args.allow_inactive_source,
            )
            print(result.report_text, end="")
            return 0

        if args.dry_run_preview:
            result = generate_dry_run_preview(
                pdf_path=override_path,
                actual_pages=args.pages,
                preview_output_path=Path(args.preview_output),
                preview_report_path=Path(args.preview_report),
                source_id=args.source_id,
                allow_inactive_source=args.allow_inactive_source,
            )
            print(result.report_text, end="")
            return 0

        result = write_content_pack(
            pdf_path=override_path,
            actual_pages=args.pages,
            preview_output_path=Path(args.preview_output),
            preview_report_path=Path(args.preview_report),
            pack_json_path=Path(args.pack_json),
            monsters_json_path=Path(args.monsters_json),
            report_path=Path(args.content_pack_report),
            source_id=args.source_id,
            allow_inactive_source=args.allow_inactive_source,
        )
    except (FileNotFoundError, RuntimeError, ValueError) as exc:
        print(str(exc), file=sys.stderr)
        return 1

    print(result.report_text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
